version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: quiz_app_postgres
    environment:
      POSTGRES_DB: quiz_app_db
      POSTGRES_USER: quiz_user
      POSTGRES_PASSWORD: quiz_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - quiz_network
    restart: unless-stopped

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: quiz_app_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - quiz_network
    restart: unless-stopped

  # Quiz Application Backend
  backend:
    build: .
    container_name: quiz_app_backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://quiz_user:quiz_password@postgres:5432/quiz_app_db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-here
      JWT_EXPIRES_IN: 24h
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./src:/app/src
      - ./prisma:/app/prisma
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - quiz_network
    restart: unless-stopped
    command: npm run dev

  # Prisma Studio (Database GUI)
  prisma-studio:
    image: node:18-alpine
    container_name: quiz_app_prisma_studio
    working_dir: /app
    environment:
      DATABASE_URL: postgresql://quiz_user:quiz_password@postgres:5432/quiz_app_db
    ports:
      - "5555:5555"
    volumes:
      - ./prisma:/app/prisma
      - ./src:/app/src
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - quiz_network
    command: npx prisma studio --hostname 0.0.0.0 --port 5555

volumes:
  postgres_data:
  redis_data:

networks:
  quiz_network:
    driver: bridge

# Health check for postgres
healthcheck:
  test: ["CMD-SHELL", "pg_isready -U quiz_user -d quiz_app_db"]
  interval: 10s
  timeout: 5s
  retries: 5
